pipeline:
  name: wifr-aggregate
description: "Aggregates model outputs under perturbations of IFR estimates in the IFR sensitivity analysis"
standby: true
transform:
  #image: paradisepilot/wifr-aggregate:1.0
  image: k8scc01covidacr.azurecr.io/daaas-kenchu-wifr-aggregate:a5a9c31d885569a7699fb66987794a6217d02c9f
  image_pull_secrets:                                                                                                  
    - k8scc01covidacr-registry-connection                 
  cmd:
    - "/main.sh"
    - "--src"
    - "/src/"
    - "--data"
    - "/pfs/data/"
    - "--output"
    - "/pfs/out"
resource_requests:
  memory: "2G"
  cpu: 2
resource_limits:
  memory: "3G"
  cpu: 3
parallelism_spec:
  constant: 2 # 100  # use N pods
output_branch: 2020-04-26_01
input:
  pfs:
    name: data
    repo: wifr-sensitivity-second
    glob: "/"
    branch: 2020-04-26_01
